### ISSUE TITLE
Supporting arbitrary length vault secrets

### ISSUE THREAD

**Issue by robinbihun** [zifeo/lade#61]
I wanted to try this out; however, our vault setup contains some very long paths and i think that is the core of our issue. 

For example:

```json
➜  vault kv get -address=https://vault.myurl.com -mount=secure -format=json division/org/team/product/feature/something

{
  "data": {
    "data": {
        "key1": "value1"
        "key2": "value2"
    }
  }
}
```
yet when setting my lade.yaml to the following i get "permission denied"

```yaml
terragrunt:
  TF_VAR_some_key: vault://vault.myurl.com/secure/division/org/team/product/feature/something/key1
```

```
┌------------------------------------------------------------------------------┐
| Lade could not get secrets from one loader:                                  |
| > Vault error: EOF while parsing a value at line 1 column 0 (stderr: Error   |
| > reading secure/data/division: Error making API request.                    |
| >                                                                            |
| > URL: GET https://vault.myurl.com/v1/secure/data/division                   |
| > Code: 403. Errors:                                                         |
| >                                                                            |
| > * 1 error occurred:                                                        |
| >     * permission denied                                                    |
| >                                                                            |
| >                                                                            |
| > )                                                                          |
| Hint: check whether the loader is connected? to the correct? vault.          |
| Waiting 5 seconds before continuing...                                       |
└------------------------------------------------------------------------------┘
```

It is worth noting, that I can also use the vault cli to get individual values by running the following:
```
➜  vault kv get -address=https://vault.myurl.com -mount=secure -field=key1 division/org/team/product/feature/something
```

**Comment by zifeo** [comment]
@robinbihun thanks for reporting, does it work with `vault://vault.myurl.com/secure/division%2Forg%2Fteam%2Fproduct%2Ffeature%2Fsomething/key1`?

In case this is not enough, can you try the verbose mode with `lade inject -vvv terragrunt`? This should give us full visibility on what happens.

**Comment by robinbihun** [comment]
No luck with the URL encoded secret string either through lade or using the commands generated by lade in vault cli directly:

This is the command that the verbose logging outputs from lade, [which makes sense from the code](https://github.com/zifeo/lade/blob/main/sdk/src/providers/vault.rs#L73C33-L73C33):
```
vault kv get -address=https://vault.myurl.com -mount=secure -format=json division%2Forg%2Fteam%2Fproduct%2Ffeature%2Fsomething
```
it returns:
```  
Error reading secure/data/division%2Forg%2Fteam%2Fproduct%2Ffeature%2Fsomething/key1: Error making API request.

URL: GET https://vault.myurl.com/v1/secure/data/division%2Forg%2Fteam%2Fproduct%2Ffeature%2Fsomething
Code: 403. Errors:

* 1 error occurred:
        * permission denied
```

**Comment by robinbihun** [comment]
I am not really familiar with rust at all; however, would something like this work on line 68 of vault.rs?

https://github.com/zifeo/lade/blob/7f107a15e4351c84708dbf161748e877dab0e1e5/sdk/src/providers/vault.rs#L68C34-L68C34
```
  url.path().split('/').get(2..url.path().split('/').collect().len()-1).expect("Missing path")
```

**Comment by zifeo** [comment]
@robinbihun Can you give a shot with `cargo install --git https://github.com/zifeo/lade --branch slash --locked`? I have enabled the urldecode for vault. Encoding the url seems to be the only way to have `/` in the field and key.

**Comment by robinbihun** [comment]
Apologies on the delay - our IT keeps blocking lade; however, i was able to run it and test this out. 

Unfortunately, the change seems to be truncating the secret path (see 'division' in the command output below instead of the full path - `division/org/team/product/feature/something/key1`

```
[2024-01-30T17:10:06Z DEBUG lade_sdk::providers::vault] Lade run: vault kv get -address=http://vault.myurl.com -mount=secure -format=json division
┌------------------------------------------------------------------------------┐
| Lade could not get secrets from one loader:                                  |
| > Vault error: EOF while parsing a value at line 1 column 0 (stderr: Error   |
| > reading secure/data/division: Error making API request.                    |
| >                                                                            |
| > URL: GET https://vault.myurl.com/v1/secure/data/division                   |
```

**Comment by zifeo** [comment]
@robinbihun I just tested again [here](https://github.com/zifeo/lade/pull/62/files#diff-a23d22b42ff11301931c6ab45ce4da4d1596d03d976639a5e5138d08dea6f0fdR24-R27) and I saw no issue. Can you verify the encoding or check if I missed something there?

**Comment by zifeo** [comment]
@robinbihun Let me know if this needs to be reopen.
