### ISSUE TITLE
Error when using raw loader

### ISSUE THREAD

**Issue by igork-ps** [zifeo/lade#72]
Content of my lade.yml
```yml
.*:
    TEST: "test-value"
```

error: 
`(eval):unset:1: test-value: invalid parameter name`

Seems like any values that have `-` in them cause this

**Comment by zifeo** [comment]
@igork-ps what is your shell? I cannot manage to reproduce with latest/fish:
![CleanShot 2024-04-25 at 22 13 27@2x](https://github.com/zifeo/lade/assets/9053709/ee81b241-1998-44b3-865b-5f91fc03d0d8)

**Comment by gregor2004ua** [comment]
I use zsh

**Comment by igork-ps** [comment]
I use ZSH

**Comment by zifeo** [comment]
@igork-ps give a try with 0.11.1, thanks for the report

**Comment by igork-ps** [comment]
works now. thank you for the fix. great tool
